### ISSUE TITLE
Testing issue for zulipbot 

### ISSUE THREAD

**Issue by Tlazypanda** [moja-global/testarea#12]
just testing out if zulipbot setup works or not

**Comment by Tlazypanda** [comment]
@ppatama claim

**Comment by Tlazypanda** [comment]
@ppatama claim

**Comment by Tlazypanda** [comment]
@ppatama abandon

**Comment by Tlazypanda** [comment]
We can have something like the welcome bot say that add labels according to the code changes done here so in this case I will add label "Cat = New Feature"

**Comment by Tlazypanda** [comment]
@ppatama label "Cat = New Feature"

**Comment by ppatama** [comment]
**ERROR:** Label "Cat = New Feature" does not exist and was thus not added to this issue.

**Comment by Tlazypanda** [comment]
ohh oops realized that this repo doesn't have this label so adding it as an admin and then testing

**Comment by Tlazypanda** [comment]
@ppatama label "Cat = New Feature"

**Comment by Tlazypanda** [comment]
Yay!! this works now testing how it works for a new contributor

**Comment by priyanka-choubey** [comment]
@ppatama claim

**Comment by ppatama** [comment]
Hello @priyanka-choubey!

Thanks for your interest in moja global! You have attempted to claim an issue without the labels "Help Wanted", "Good for newcomers". Since you're a new contributor, you can only claim and submit pull requests for issues with the [Help Wanted](https://github.com/moja-global/testarea/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22Help+Wanted%22) or [Good for newcomers](https://github.com/moja-global/testarea/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22Good+for+newcomers%22) labels.

**Comment by priyanka-choubey** [comment]
@ppatama claim

**Comment by ppatama** [comment]
Welcome to moja global, @priyanka-choubey! We just sent you an invite to collaborate on this repository at https://github.com/moja-global/testarea/invitations. Please accept this invite in order to claim this issue and begin a fun, rewarding experience contributing to Zulip!

Here's some tips to get you off to a good start:
* Join me on the [Zulip developers' server](https://chat.zulip.org), to get help, chat about this issue, and meet the other developers.
* [Unwatch this repository](https://help.github.com/articles/unwatching-repositories/), so that you don't get 100 emails a day.

As you work on this issue, you'll also want to refer to the [Zulip code contribution guide](https://zulip.readthedocs.io/en/latest/contributing/index.html), as well as the rest of the developer documentation on that site.

See you on the other side (that is, the pull request side)!

**Comment by priyanka-choubey** [comment]
Okay this message needs to be edited but apart from that, let's test what happens if someone else tries to claim this issue when it has already been claimed

**Comment by Tlazypanda** [comment]
@ppatama claim

**Comment by ppatama** [comment]
Hello @Tlazypanda, it looks like someone has already claimed this issue! Since we believe multiple assignments to the same issue may cause some confusion, we encourage you to search for other unclaimed issues to work on. However, you can always reclaim this issue if no one is working on it.

We look forward to your valuable contributions!

**Comment by Tlazypanda** [comment]
see closed automatically
